# action.yml
name: 'redoc-cli and speccy'
description: 'run redoc-cli and speccy tasks'
inputs:
  redoc-args:
    description: 'Arguments for redoc'
    required: false
  speccy-args:
    description: 'Arguments for speccy'
    required: false
outputs:
  time: # id of output
    description: 'The time this ran'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.redoc-args }}
    - ${{ inputs.speccy-args }}
