# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  redoc-args:
    description: 'Arguments for redoc'
    required: false
  speccy-args:
    description: 'Arguments for speccy'
    required: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.redoc-args }}
    - ${{ inputs.speccy-args }}
